# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_location_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='profpic',
            field=models.ImageField(blank=True, upload_to='driver-profpic/'),
        ),
    ]
