# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0007_riderreview'),
        ('driver', '0005_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.DriverProfile')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider.RiderProfile')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider.Travel')),
            ],
        ),
    ]
