# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_auto_20171202_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='profpic',
            field=models.ImageField(blank=True, default=False, upload_to='rider-profpic/'),
        ),
    ]
