# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='profpic',
            field=models.ImageField(blank=True, upload_to='rider-profpic/'),
        ),
    ]
