# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_auto_20171204_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='gen_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
